### ISSUE TITLE
Iterators are not suited for multi threaded applications

### ISSUE THREAD

**Issue by rourke750** [TealNerd/RadarJammer#5]
https://github.com/TealNerd/RadarJammer/blob/master/src/com/biggestnerd/radarjammer/VisibilityManager.java#L271 throwing a concurent modification exception.

possible reason is https://github.com/TealNerd/RadarJammer/blob/master/src/com/biggestnerd/radarjammer/VisibilityManager.java#L311
adding a uuid while the iterator is going through.  Blocking queue is maybe what you are looking for.
One solution http://stackoverflow.com/questions/5893096/how-to-make-a-concurrent-iterator-over-some-source
http://docs.oracle.com/javase/1.5.0/docs/api/java/util/concurrent/BlockingQueue.html

**Comment by TealNerd** [comment]
the linkedhashset there used to be a queue but it wasnt bounded so theoretically could have gotten out of control if the server wasn't processing players as fast as they were moving. using a linkedhashset would preserve insertion order while having unique values

**Comment by rourke750** [comment]
Don't use an iterator to loop then. Run through a normal for loop.

**Comment by rourke750** [comment]
Or use a synchronized tag when looping.  You are still getting concurrent exceptions

**Comment by TealNerd** [comment]
yeah i dont actually remember why i used an iterator instead of a for loop
